apiVersion: v1
kind: Service
metadata:
  name: eks-customer-service
  labels:
    app: eks-customer-app
spec:
  type: LoadBalancer
  selector:
    app: eks-customer-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080