name: Build ECR image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: aws

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
        exclude: []

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate on AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      - name: Connecting to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t customer:latest .

      - name: Publish to ECR
        env:
          ECR_URL: ""
        run: |    
          docker tag customer:latest $ECR_URL/customer:latest
          docker push $ECR_URL/customer:latest
